# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Actualités
    url: post
    weight: 10
  - name: Équipe
    url: people
    weight: 22
  - name: Presse
    url: post
    weight: 30
  - name: L'intégrale
    url: publication
    weight: 21
  - name: Événements
    url: event
    weight: 50
  - name: Boutique
    url: boutique
    weight: 60
  - name: Contact
    url: contact
    weight: 70
